#!/usr/bin/env sh

# Lint frontend staged files
if git diff --cached --name-only | grep -q '^frontend/'; then
  cd frontend && npx lint-staged && cd ..
fi

# Lint backend staged files
if git diff --cached --name-only | grep -q '^backend/'; then
  cd backend && npx lint-staged
fi
